version: '3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dibyendubiswas1998/myapp2:latest  # Explicitly define the image name and tag
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
    restart: always
